=== kunalPisolkar24/WT_Lab/three/employees.dtd
<!ELEMENT employees (employee*)>
<!ELEMENT employee (name, position, department)>
<!ATTLIST employee id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT department (#PCDATA)>

=== kunalPisolkar24/WT_Lab/three/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    <employee id="1">
        <name>John Doe</name>
        <position>Software Engineer</position>
        <department>IT</department>
    </employee>
    <employee id="2">
        <name>Jane Smith</name>
        <position>HR Manager</position>
        <department>Human Resources</department>
    </employee>
    <employee id="3">
        <name>Emily Johnson</name>
        <position>Marketing Specialist</position>
        <department>Marketing</department>
    </employee>
    <employee id="4">
        <name>Michael Brown</name>
        <position>Product Manager</position>
        <department>Product</department>
    </employee>
    <employee id="5">
        <name>Sarah Davis</name>
        <position>Data Analyst</position>
        <department>Data</department>
    </employee>
</employees>
